# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hashed_token', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('refresh', 'refresh')], default='refresh', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_au_user_id_4aef18_idx'), models.Index(fields=['expires_at'], name='accounts_au_expires_0a3b67_idx'), models.Index(fields=['revoked_at'], name='accounts_au_revoked_885cf5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__isnull', False)), name='auth_token_expires_not_null')],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'google'), ('github', 'github')], max_length=20)),
                ('provider_uid', models.CharField(max_length=255, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider'], name='accounts_oa_provide_4609ae_idx'), models.Index(fields=['user'], name='accounts_oa_user_id_18cba3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_id_3b7362_idx'), models.Index(fields=['user'], name='accounts_us_user_id_d06a5b_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
