# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('pt', 'pt'), ('en', 'en'), ('es', 'es')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('slug_locale', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='taxonomy.category')),
            ],
            options={
                'indexes': [models.Index(fields=['locale'], name='taxonomy_ca_locale_323c26_idx'), models.Index(fields=['slug_locale'], name='taxonomy_ca_slug_lo_f69b68_idx'), models.Index(fields=['name'], name='taxonomy_ca_name_0538c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug_locale'), name='unique_category_slug_per_locale')],
                'unique_together': {('category', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='taxonomy_po_categor_64e2e2_idx'), models.Index(fields=['post'], name='taxonomy_po_post_id_3de4ff_idx')],
                'unique_together': {('post', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['tag'], name='taxonomy_po_tag_id_bc6039_idx'), models.Index(fields=['post'], name='taxonomy_po_post_id_85fb6f_idx')],
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='TagLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('pt', 'pt'), ('en', 'en'), ('es', 'es')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('slug_locale', models.SlugField(max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='taxonomy.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['locale'], name='taxonomy_ta_locale_e6ace5_idx'), models.Index(fields=['slug_locale'], name='taxonomy_ta_slug_lo_4b3199_idx'), models.Index(fields=['name'], name='taxonomy_ta_name_56e325_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug_locale'), name='unique_tag_slug_per_locale')],
                'unique_together': {('tag', 'locale')},
            },
        ),
    ]
