# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_base', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('review', 'review'), ('scheduled', 'scheduled'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_posts', to='media.mediaasset')),
            ],
        ),
        migrations.CreateModel(
            name='PostLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('pt', 'pt'), ('en', 'en'), ('es', 'es')], max_length=3)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('body_md', models.TextField()),
                ('body_html', models.TextField()),
                ('slug_locale', models.SlugField(max_length=255)),
                ('seo_title', models.CharField(blank=True, max_length=300)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=300)),
                ('og_description', models.CharField(blank=True, max_length=500)),
                ('reading_time_words', models.PositiveIntegerField(default=0)),
                ('og_image_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='og_image_posts', to='media.mediaasset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('pt', 'pt'), ('en', 'en'), ('es', 'es')], max_length=3)),
                ('diff_md', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.post')),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='blog_post_status_02ce19_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published_at'], name='blog_post_publish_698bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured'], name='blog_post_is_feat_837e2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='post_published_requires_date'),
        ),
        migrations.AddIndex(
            model_name='postlocale',
            index=models.Index(fields=['locale'], name='blog_postlo_locale_f5b689_idx'),
        ),
        migrations.AddIndex(
            model_name='postlocale',
            index=models.Index(fields=['slug_locale'], name='blog_postlo_slug_lo_256b32_idx'),
        ),
        migrations.AddIndex(
            model_name='postlocale',
            index=models.Index(fields=['title'], name='blog_postlo_title_9017b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='postlocale',
            constraint=models.UniqueConstraint(fields=('locale', 'slug_locale'), name='unique_slug_per_locale'),
        ),
        migrations.AlterUniqueTogether(
            name='postlocale',
            unique_together={('post', 'locale')},
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=models.Index(fields=['post', 'locale'], name='blog_postre_post_id_a824a7_idx'),
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=models.Index(fields=['created_at'], name='blog_postre_created_ec7a4f_idx'),
        ),
    ]
