# Generated by Django 5.2.1 on 2025-12-18 14:14

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postlocale_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlocale',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
