# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedProviderWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='blog.postlocale')),
                ('provider_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embeds', to='embeds.embedproviderwhitelist')),
            ],
            options={
                'indexes': [models.Index(fields=['post_locale'], name='embeds_embe_post_lo_263d2d_idx'), models.Index(fields=['provider_domain'], name='embeds_embe_provide_09b939_idx'), models.Index(fields=['position'], name='embeds_embe_positio_b23931_idx')],
            },
        ),
    ]
