# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('post', 'post'), ('comment', 'comment'), ('media', 'media'), ('post_locale', 'post_locale')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('event', models.CharField(choices=[('publish', 'publish'), ('update', 'update'), ('delete', 'delete'), ('comment_approved', 'comment_approved')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='seo_content_entity__e3df8c_idx'), models.Index(fields=['event'], name='seo_content_event_fd2586_idx'), models.Index(fields=['created_at'], name='seo_content_created_b0162e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('publish', 'publish'), ('schedule', 'schedule'), ('login', 'login')], max_length=20)),
                ('entity_type', models.CharField(choices=[('post', 'post'), ('comment', 'comment'), ('media', 'media'), ('post_locale', 'post_locale')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('diff', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action'], name='seo_auditlo_action_6ed59f_idx'), models.Index(fields=['entity_type', 'entity_id'], name='seo_auditlo_entity__4c5ea0_idx'), models.Index(fields=['created_at'], name='seo_auditlo_created_d2be83_idx')],
            },
        ),
    ]
