# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_provider', models.CharField(choices=[('local', 'local'), ('s3', 's3'), ('gcs', 'gcs')], default='local', max_length=20)),
                ('path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mime_type'], name='media_media_mime_ty_c915f1_idx'), models.Index(fields=['created_at'], name='media_media_created_351a52_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('post', 'post'), ('post_locale', 'post_locale'), ('comment', 'comment')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(choices=[('cover', 'cover'), ('inline', 'inline'), ('og', 'og')], max_length=20)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='media.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='media_media_entity__27a3ed_idx'), models.Index(fields=['purpose'], name='media_media_purpose_0b7137_idx')],
                'unique_together': {('media', 'entity_type', 'entity_id', 'purpose')},
            },
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('webp', 'webp'), ('avif', 'avif'), ('jpg', 'jpg'), ('png', 'png')], max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['format'], name='media_media_format_e02b2a_idx'), models.Index(fields=['width', 'height'], name='media_media_width_916f03_idx')],
            },
        ),
    ]
