# Generated by Django 5.2.1 on 2025-12-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('flagged', 'flagged'), ('spam', 'spam')], default='pending', max_length=20)),
                ('spam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('flag', 'flag'), ('unflag', 'unflag')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='comments.comment')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_moderations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('clap', 'clap'), ('love', 'love')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('clap', 'clap'), ('love', 'love')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'status', 'created_at'], name='comments_co_post_id_c397d3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_co_parent__fdf1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmoderation',
            index=models.Index(fields=['comment'], name='comments_co_comment_2a4925_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmoderation',
            index=models.Index(fields=['performed_by'], name='comments_co_perform_fb9edc_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmoderation',
            index=models.Index(fields=['created_at'], name='comments_co_created_764d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['comment'], name='comments_co_comment_f49c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['type'], name='comments_co_type_ed54d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment', 'user', 'type'), name='unique_comment_user_reaction'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['post'], name='comments_po_post_id_0b15ac_idx'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['type'], name='comments_po_type_488e96_idx'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user', 'type'), name='unique_post_user_reaction'),
        ),
    ]
